import { PODFileType } from "./types";

type PODFileItem<T> = {
    [P in keyof T]: { field: P; columnName: string; value: T[P] };
  }[keyof T];
  export const PODFileColumns: PODFileItem<PODFileType>[] = [
      { field: 'Name', columnName: 'Name', value: '' },
      { field: 'Email', columnName: 'Email', value: null },
      { field: 'FulfillmentStatus', columnName: 'Fulfillment Status', value: null },
      { field: 'FulfilledAt', columnName: 'Fulfilled at', value: null },
      { field: 'Shipping', columnName: 'Shipping', value: 0 },
      { field: 'ShippingMethod', columnName: 'Shipping Method', value: null },
      { field: 'CreatedAt', columnName: 'Created At', value: '' },
      { field: 'LineitemQuantity', columnName: 'Lineitem Quantity', value: 0 },
      { field: 'LineitemName', columnName: 'Lineitem Name', value: '' },
      { field: 'LineitemSku', columnName: 'Lineitem sku', value: null },
      { field: 'BillingName', columnName: 'Billing Name', value: null },
      { field: 'BillingStreet', columnName: 'Billing Street', value: null },
      { field: 'BillingAddress1', columnName: 'Billing Address 1', value: null },
      { field: 'BillingAddress2', columnName: 'Billing Address 2', value: null },
      { field: 'BillingCompany', columnName: 'Billing Company', value: null },
      { field: 'BillingCity', columnName: 'Billing City', value: null },
      { field: 'BillingZip', columnName: 'Billing Zip', value: null },
      { field: 'BillingProvince', columnName: 'Billing Province', value: null },
      { field: 'BillingCountry', columnName: 'Billing Country', value: null },
      { field: 'BillingPhone', columnName: 'Billing Phone', value: null },
      { field: 'ShippingName', columnName: 'Shipping Name', value: null },
      { field: 'ShippingStreet', columnName: 'Shipping Street', value: null },
      { field: 'ShippingAddress1', columnName: 'Shipping Address 1', value: null },
      { field: 'ShippingAddress2', columnName: 'Shipping Address 2', value: null },
      { field: 'ShippingCompany', columnName: 'Shipping Company', value: null },
      { field: 'ShippingCity', columnName: 'Shipping City', value: null },
      { field: 'ShippingZip', columnName: 'Shipping Zip', value: null },
      { field: 'ShippingProvince', columnName: 'Shipping Province', value: null },
      { field: 'ShippingCountry', columnName: 'Shipping Country', value: null },
      { field: 'ShippingPhone', columnName: 'Shipping Phone', value: null },
      { field: 'Notes', columnName: 'Notes', value: null },
      { field: 'NoteAttributes', columnName: 'Note Attributes', value: null },
      { field: 'CancelledAt', columnName: 'Cancelled At', value: null },
      { field: 'Vendor', columnName: 'Vendor', value: null },
      { field: 'Location', columnName: 'Location', value: null },
      { field: 'Id', columnName: 'ID', value: 0 },
      { field: 'Tags', columnName: 'Tags', value: null },
      { field: 'Source', columnName: 'Source', value: null },
      { field: 'Phone', columnName: 'Phone', value: null },
      { field: 'ReceiptNumber', columnName: 'Receipt Number', value: null },
      {
        field: 'BillingProvinceName',
        columnName: 'Billing Province Name',
        value: null,
      },
      {
        field: 'ShippingProvinceName',
        columnName: 'Shipping Province Name',
        value: null,
      },
    ];