import { v4 } from "uuid";
import { CMIObjectType } from "./designHooks.client";

export const testObjects:CMIObjectType[] = [
    {
      id: v4().toString(),
      height: 150,
      type: 'image',
      src: 'https://picsum.photos/id/237/200/300',
      rotation: 0,
      width: 150,
      x: 25,
      y: 25,
    },
    {
      id:  v4().toString(),
      height: 150,
      type: 'image',
      src: 'https://picsum.photos/id/237/200/300',
      rotation: 0,
      width: 150,
      x: 25,
      y: 25,
    },
    {
      id:  v4().toString(),
      height: 150,
      type: 'image',
      src: 'https://picsum.photos/id/237/200/300',
      rotation: 0,
      width: 150,
      x: 25,
      y: 25,
    },
    {
      id:  v4().toString(),
      height: 150,
      type: 'image',
      src: 'https://picsum.photos/id/237/200/300',
      rotation: 0,
      width: 150,
      x: 25,
      y: 25,
    },
    {
      id:  v4().toString(),
      height: 150,
      type: 'image',
      src: 'https://picsum.photos/id/237/200/300',
      rotation: 0,
      width: 150,
      x: 25,
      y: 25,
    },
    {
      id:  v4().toString(),
      height: 150,
      type: 'image',
      src: 'https://picsum.photos/id/237/200/300',
      rotation: 0,
      width: 150,
      x: 25,
      y: 25,
    },
    {
      id:  v4().toString(),
      height: 150,
      type: 'image',
      src: 'https://picsum.photos/id/237/200/300',
      rotation: 0,
      width: 150,
      x: 25,
      y: 25,
    },
    {
      id:  v4().toString(),
      height: 150,
      type: 'image',
      src: 'https://picsum.photos/id/237/200/300',
      rotation: 0,
      width: 150,
      x: 25,
      y: 25,
    },
    {
      id: 'asdefasdc',

      type: 'text',

      rotation: 0,
      x: 25,
      y: 25,
      fontSize: 25,
      fontFamily: '',
      text: 'sdegfvsdfgvsdfgsxdcfvsdvsdfvsfdvsxdfvsdouvhnbisbvuysbvivibvisdbnvibnvisbnvisbnvsidnvi',
      fill: 'green',
    },
  ]