import { PODFileType } from './types';
import * as yup from 'yup';
type PODFileItem<T> = {
  [P in keyof T]: { field: P; columnName: string; value: T[P] };
}[keyof T];
export const PODFileColumns: PODFileItem<PODFileType>[] = [
  { field: 'Name', columnName: 'Name', value: '' },
  { field: 'orderId', columnName: 'Order Id', value: '' },
  { field: 'Email', columnName: 'Email', value: null },
  { field: 'LineitemQuantity', columnName: 'Lineitem Quantity', value: 0 },
  { field: 'LineitemName', columnName: 'Lineitem Name', value: '' },
  { field: 'LineitemSku', columnName: 'Lineitem sku', value: null },
  { field: 'BillingName', columnName: 'Billing Name', value: null },
  { field: 'BillingStreet', columnName: 'Billing Street', value: null },
  { field: 'BillingAddress1', columnName: 'Billing Address 1', value: null },
  { field: 'BillingAddress2', columnName: 'Billing Address 2', value: null },
  { field: 'BillingCompany', columnName: 'Billing Company', value: null },
  { field: 'BillingCity', columnName: 'Billing City', value: null },
  { field: 'BillingZip', columnName: 'Billing Zip', value: null },
  { field: 'BillingProvince', columnName: 'Billing Province', value: null },
  { field: 'BillingCountry', columnName: 'Billing Country', value: null },
  { field: 'BillingPhone', columnName: 'Billing Phone', value: null },
  { field: 'ShippingName', columnName: 'Shipping Name', value: null },
  { field: 'ShippingStreet', columnName: 'Shipping Street', value: null },
  { field: 'ShippingAddress1', columnName: 'Shipping Address 1', value: null },
  { field: 'ShippingAddress2', columnName: 'Shipping Address 2', value: null },
  { field: 'ShippingCompany', columnName: 'Shipping Company', value: null },
  { field: 'ShippingCity', columnName: 'Shipping City', value: null },
  { field: 'ShippingZip', columnName: 'Shipping Zip', value: null },
  { field: 'ShippingProvince', columnName: 'Shipping Province', value: null },
  { field: 'ShippingCountry', columnName: 'Shipping Country', value: null },
  { field: 'ShippingPhone', columnName: 'Shipping Phone', value: null },
  { field: 'Notes', columnName: 'Notes', value: null },
  { field: 'NoteAttributes', columnName: 'Note Attributes', value: null },
  { field: 'Location', columnName: 'Location', value: null },
  { field: 'Id', columnName: 'ID', value: 0 },
  { field: 'Tags', columnName: 'Tags', value: null },
  { field: 'Phone', columnName: 'Phone', value: null },
  { field: 'ReceiptNumber', columnName: 'Receipt Number', value: null },
  {
    field: 'BillingProvinceName',
    columnName: 'Billing Province Name',
    value: null,
  },
  {
    field: 'ShippingProvinceName',
    columnName: 'Shipping Province Name',
    value: null,
  },
];

export const PODTypeSchema = yup.object().shape({
      orderId: yup.string().required('Order ID is required'),
      Name: yup.string().required('Name is required'),
      Email: yup.string().nullable().email('Invalid email format'),
      LineitemQuantity: yup.number().min(1,"min qty is 1").required('Lineitem quantity is required'),
      LineitemName: yup.string().required('Lineitem name is required'),
      LineitemSku: yup.string().nullable(),
      BillingName: yup.string().nullable(),
      BillingStreet: yup.string().nullable(),
      BillingAddress1: yup.string().nullable(),
      BillingAddress2: yup.string().nullable(),
      BillingCompany: yup.string().nullable(),
      BillingCity: yup.string().nullable(),
      BillingZip: yup.string().nullable(),
      BillingProvince: yup.string().nullable(),
      BillingCountry: yup.string().nullable(),
      BillingPhone: yup.string().nullable(),
      ShippingName: yup.string().required('Shipping name is required'),
      ShippingStreet: yup.string().required('Shipping street is required'),
      ShippingAddress1: yup.string().required('Shipping address 1 is required'),
      ShippingAddress2: yup.string().required('Shipping address 2 is required'),
      ShippingCompany: yup.string().required('Shipping company is required'),
      ShippingCity: yup.string().required('Shipping city is required'),
      ShippingZip: yup.string().required('Shipping zip is required'),
      ShippingProvince: yup.string().required('Shipping province is required'),
      ShippingCountry: yup.string().required('Shipping country is required'),
      ShippingPhone: yup.string().required('Shipping phone is required'),
      Notes: yup.string().nullable(),
      NoteAttributes: yup.string().nullable(),
      Location: yup.string().nullable(),
      Id: yup.number().nullable(),
      Tags: yup.string().nullable(),
      Phone: yup.string().nullable(),
      ReceiptNumber: yup.string().nullable(),
      BillingProvinceName: yup.string().nullable(),
      ShippingProvinceName: yup.string().nullable(),
      design: yup.object().required('Design is required'), // Replace with appropriate validation if CMIProductDesignType has a specific structure
    })
